export const formatViews = (views) => Number(views || 0).toLocaleString('vi-VN')

export const getUniqueGenres = (movies) => ['Tất cả', ...Array.from(new Set(movies.map((movie) => movie.genreName)))]

export const demoMovies = [
  {
    _id: 'm1',
    title: 'Neon Horizon',
    description: 'Một shipper băng qua siêu đô thị rực sáng để giao bí mật có thể khởi động lại tương lai.',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    genreName: 'Sci-Fi',
    quality: '4K',
    rating: 4.8,
    duration: 118,
    views: 12420,
    featured: true,
  },
  {
    _id: 'm2',
    title: 'Last Frame',
    description: 'Một nhiếp ảnh gia nghỉ hưu quay lại thành phố nơi bức ảnh dang dở từng thay đổi đời ông.',
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    genreName: 'Drama',
    quality: 'FHD',
    rating: 4.6,
    duration: 104,
    views: 8320,
    featured: true,
  },
  {
    _id: 'm3',
    title: 'Midnight Chase',
    description: 'Hai người xa lạ có một đêm để lật tẩy đường dây buôn lậu ẩn dưới bến cảng.',
    posterUrl: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    genreName: 'Action',
    quality: '4K',
    rating: 4.5,
    duration: 126,
    views: 15480,
    featured: true,
  },
  {
    _id: 'm4',
    title: 'Quiet Signal',
    description: 'Một kỹ sư âm thanh nghe thấy tín hiệu cũ dẫn về vụ mất tích chưa từng được công bố.',
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    genreName: 'Mystery',
    quality: 'HD',
    rating: 4.3,
    duration: 99,
    views: 6750,
    featured: false,
  },
  {
    _id: 'm5',
    title: 'Paper Hearts',
    description: 'Chuyện tình nhẹ nhàng giữa hai người trẻ giữa lòng Hà Nội mùa thu.',
    posterUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    genreName: 'Romance',
    quality: 'FHD',
    rating: 4.2,
    duration: 92,
    views: 5430,
    featured: false,
  },
  {
    _id: 'm6',
    title: 'Shadow Realm',
    description: 'Một streamer bước vào game kinh dị thực tế ảo và phát hiện ranh giới thật - ảo đang mờ dần.',
    posterUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    genreName: 'Horror',
    quality: '4K',
    rating: 4.4,
    duration: 108,
    views: 9870,
    featured: true,
  },
  {
    _id: 'm7',
    title: 'Skyline Drift',
    description: 'Đường đua bất hợp pháp trên những con phố neon, nơi tốc độ là vua và tử thần là khán giả.',
    posterUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    genreName: 'Action',
    quality: '4K',
    rating: 4.7,
    duration: 132,
    views: 18230,
    featured: false,
  },
  {
    _id: 'm8',
    title: 'Echoes of Tomorrow',
    description: 'Một nhà khoa học nhận được lá thư từ chính mình ở 30 năm sau, kèm một lời cảnh báo.',
    posterUrl: 'https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    genreName: 'Sci-Fi',
    quality: 'FHD',
    rating: 4.5,
    duration: 121,
    views: 7610,
    featured: false,
  },
  {
    _id: 'm9',
    title: 'Lồng Son',
    description: 'Câu chuyện cổ tích Việt Nam được tái hiện với hình ảnh hoạt hình hiện đại đầy mê hoặc.',
    posterUrl: 'https://images.unsplash.com/photo-1502139214982-d0ad755818d8?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    genreName: 'Animation',
    quality: '4K',
    rating: 4.9,
    duration: 95,
    views: 22000,
    featured: true,
  },
  {
    _id: 'm10',
    title: 'Silent Code',
    description: 'Lập trình viên trẻ khám phá ra thuật toán có thể dự đoán tương lai trong 7 ngày.',
    posterUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    genreName: 'Sci-Fi',
    quality: 'HD',
    rating: 4.1,
    duration: 88,
    views: 4320,
    featured: false,
  },
]

export const demoComments = [
  {
    _id: 'c1',
    movieId: 'm1',
    authorName: 'Linh',
    content: 'Hình ảnh đẹp, nhịp phim cuốn.',
    createdAt: new Date().toISOString(),
  },
]
